baseURL: https://donsan.org
title: David Sepashvili
theme: DoIt
enableEmoji: true

menu:
  main:
    - identifier: home
      name: Home
      url: "/"
      weight: 1
    - identifier: projects
      name: Projects
      url: "/projects/"
      weight: 2
    # - identifier: about
    #   name: About
    #   url: "/about/"
    #   weight: 99


params:
  version: 0.3.X
  title: David Sepashvili
  description: Security Engineer from London
  keywords:
    - David Sepashvili
    - Security Engineer
    - Security
    - Personal Website
    - Blog
    - donsan
    - donsansec
    - Sepashvili
  fingerprint: sha512
  dateFormat: "2006-01-02"
  images: ["/me.jpeg"]
  optimizeImages: true

  home:
    profile:
      enable: True
      avatarUrl: /me.jpeg
      title: David Sepashvili
      subtitle: Security Engineer based in London
      typeit: False
      social: True
    posts:
      enable: False
  social:
    Github: don-san-sec
    Linkedin: donsan
    Twitter: donsansec

  footer:
    enable: False
  cookieconsent:
    enable: False
  page:
    hiddenFromHomePage: False
    hiddenFromSearch: False
    twemoji: False
    lightgallery: False
    ruby: True
    fraction: True
    fontawesome: True
    rssFullText: True
    pageStyle: wide
    seriesNavigation: True
    toc:
      enable: True
      keepStatic: False
      auto: True
    math:
      enable: True
      copyTex: True
      mhchem: True
    code:
      copy: True
      maxShownLines: 10
    table:
      sort: True
    share:
      enable: False
    comment:
      enable: False
  twitterCard: # https://github.com/dereckcurry/hugo-configurable-twitter-cards
    generate: False
    card: "summary"

author:
  name: "David Sepashvili"
  email: "don-san-sec@pm.me"



markup:
  highlight:
    codeFences: True
    guessSyntax: True
    lineNos: True
    lineNumbersInTable: True
    noClasses: False
  goldmark:
    extensions:
      definitionList: True
      footnote: True
      linkify: True
      strikethrough: True
      table: True
      taskList: True
      typographer: True
    renderer:
      unsafe: True
    tableOfContents:
      startLevel: 2
      endLevel: 6